### ISSUE TITLE
Написать Makefile

### ISSUE THREAD

**Issue by amayakasa** [Rasmus8800/c3po#11]
Нам нужно написать **`Makefile`** из которого можно будет запускать линтеры, проверку типов и тесты.

Предлагаю следующие названия:
* `make style` — для запуска линтеров.
* `make types` — для запуска проверки типов.
* `make tests` — для запуска тестов.

Позже добавим туда дополнительные задачи.

**Comment by Rasmus8800** [comment]
Сделал в #12
